name: noise2void
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - astropy=5.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blinker=1.4
  - blosc=1.21.3
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cachetools=4.2.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - cryptography=38.0.4
  - cudatoolkit=11.3.1
  - cudnn=8.4.1.50
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - defusedxml=0.7.1
  - fpdf2=2.7.5
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.39.1
  - grpcio=1.39.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - joblib=1.1.1
  - jpeg=9e
  - jxrlib=1.1
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - krb5=1.19.4
  - lcms2=2.15
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.84.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - llvmlite=0.38.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - multidict=6.0.2
  - munkres=1.1.4
  - nccl=2.14.3.1
  - ncurses=6.4
  - numba=0.55.1
  - numpy=1.19.5
  - oauthlib=3.2.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - partd=1.2.0
  - pip=22.2.1
  - protobuf=3.16.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyerfa=2.0.0.1
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.13
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pywavelets=1.4.1
  - pyyaml=6.0
  - re2=2021.09.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.19.3
  - scikit-learn=1.2.0
  - scipy=1.8.1
  - setproctitle=1.2.3
  - setuptools=65.6.3
  - six=1.15.0
  - snappy=1.1.9
  - sqlite=3.39.3
  - tbb=2021.6.0
  - tensorboard=2.9.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toolz=0.12.0
  - typing_extensions=3.7.4.3
  - tzdata=2022a
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wget=1.21.4
  - wheel=0.37.1
  - wrapt=1.12.1
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.1
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - altgraph==0.17.3
    - csbdeep==0.7.4
    - cycler==0.11.0
    - fonttools==4.38.0
    - future==0.18.3
    - imagecodecs==2023.9.18
    - imageio==2.20.0
    - itk==5.2.1
    - itk-core==5.2.1
    - itk-filtering==5.2.1
    - itk-io==5.2.1
    - itk-numerics==5.2.1
    - itk-registration==5.2.1
    - itk-segmentation==5.2.1
    - kiwisolver==1.4.4
    - matplotlib==3.5.2
    - n2v==0.3.2
    - networkx==2.8.5
    - nibabel==4.0.1
    - opencv-python-headless==4.7.0.68
    - packaging==23.0
    - pandas==1.4.3
    - pillow==9.4.0
    - pyinstaller==5.8.0
    - pyinstaller-hooks-contrib==2023.0
    - pyparsing==3.0.9
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - simpleitk==2.1.1.2
    - tifffile==2022.7.28
    - tqdm==4.64.0
    - treelib==1.6.1
    - vtk==9.1.0
    - wslink==1.10.1
